import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  agentRules: false,
  distDir: process.env.NEXT_DIST_DIR ?? ".next",
  output: "standalone",
  outputFileTracingIncludes: {
    "/api/accounts/*/import/extract": [
      "./scripts/extract-import-source.mjs",
      ...[
        "pdfjs-dist",
        "@napi-rs",
        "@nodable",
        "@xmldom",
        "yauzl",
        "pend",
        "fast-xml-parser",
        "fast-xml-builder",
        "strnum",
        "xml-naming",
        "anynum",
        "path-expression-matcher",
        "is-unsafe",
        "mammoth",
        "jszip",
        "pako",
        "lie",
        "immediate",
        "setimmediate",
        "readable-stream",
        "core-util-is",
        "inherits",
        "isarray",
        "process-nextick-args",
        "safe-buffer",
        "string_decoder",
        "util-deprecate",
        "bluebird",
        "argparse",
        "base64-js",
        "dingbat-to-unicode",
        "underscore",
        "lop",
        "option",
        "duck",
        "path-is-absolute",
        "xmlbuilder",
        "sprintf-js",
      ].map((name) => `./node_modules/${name}/**/*`),
    ],
  },
  poweredByHeader: false,
  allowedDevOrigins: ["127.0.0.1"],
  experimental: {
    serverActions: {
      bodySizeLimit: "12mb",
    },
  },
};

export default nextConfig;
